-- Broiler Monitor — Supabase tables
-- Run this once in your Supabase project: SQL Editor -> New query -> paste -> Run.

-- NOTE: ts is a plain `timestamp` (no time zone). We store LOCAL wall-clock time
-- (Malaysia / MYT) so the raw rows here match your clock on a single-site setup.

create table if not exists readings (
  id              bigint generated by default as identity primary key,
  ts              timestamp not null default (now() at time zone 'Asia/Kuala_Lumpur'),
  feeder_type     text,
  feed_kg         double precision,
  fill_ratio      double precision,
  chicken_count   integer,
  temperature_c   double precision,
  humidity_pct    double precision,
  thi_c           double precision,
  required_kg     double precision,
  feed_to_add_kg  double precision,
  coverage_pct    double precision
);

create table if not exists alerts (
  id        bigint generated by default as identity primary key,
  ts        timestamp not null default (now() at time zone 'Asia/Kuala_Lumpur'),
  kind      text,
  message   text,
  value     double precision
);

create index if not exists readings_ts_idx on readings (ts desc);
create index if not exists alerts_ts_idx    on alerts (ts desc);

-- The worker writes using your API key. If you use the public "anon" key and
-- Row Level Security is ON, add permissive policies (fine for a private FYP
-- project; tighten for production):
alter table readings enable row level security;
alter table alerts   enable row level security;

drop policy if exists readings_all on readings;
drop policy if exists alerts_all   on alerts;
create policy readings_all on readings for all using (true) with check (true);
create policy alerts_all   on alerts   for all using (true) with check (true);

-- Simplest alternative: use the SERVICE ROLE key in monitor_config.json (it
-- bypasses RLS) and you can skip the policies above.
